name: 'GitHub Actions CloudFlare2DNSPod Bot'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '*/15 * * * *'

env:
  UPDATE_IPV4: true
  UPDATE_IPV6: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: 'Cache pip dependencies'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: 'Install dependencies'
        run: |
          if [ -f requirements.txt ]; then
            # 使用缓存路径安装依赖
            pip install --cache-dir ~/.cache/pip -r requirements.txt
          fi
      - name: 'run cf2dns v4'
        if: env.UPDATE_IPV4 == 'true' && !cancelled()
        env:
          KEY: ${{ secrets.KEY }}
          DOMAINS: ${{ secrets.DOMAINS }}
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
        run: python cf2dns_actions.py A
      - name: 'run cf2dns v6'
        if: env.UPDATE_IPV6 == 'true' && !cancelled()
        env:
          KEY: ${{ secrets.KEY }}
          DOMAINS: ${{ secrets.DOMAINSV6 }}
          SECRETID: ${{ secrets.SECRETID }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
        run: python cf2dns_actions.py AAAA
